config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'
  namespace :public do
    #Homes

    get 'about' => "homes#about"
    #Items
    resources :items, only: [:index, :show]
    #Registration
    resources :registrations, only: [:new, :create]
    #Sessions
    resources :sessions, only: [:new, :create, :destroy]
    #Customers
    get "customers/home" => "customers#show"
    get "customers/edit" => "customers#edit"
    patch "customers" => "customers#update"
    get "customers/confimation" => "customers#confimation"
    patch "customers/confimation" => "customers#withdraw", as: :withdraw_customer
    #Cart_Items
    get "cart_items" => "cart_items#index"
    patch "cart_items/:id" => "cart_items#update", as: :update_cart_item
    delete "cart_items/:id/destroy" => "cart_items#destroy", as: :destroy_cart_item
    delete "cart_items/destroy_all" => "cart_items#destroy_all", as: :destroy_all_cart_item
    post "cart_items" => "cart_items#create", as: :create_cart_item
    #Orders
    get "orders" => "orders#index"
    get "orders/new" => "orders#new"
    post "orders/new" => "orders#create"
    post "orders/confimation" => "orders#confimation"
    get "orders/thanks" => "orders#thanks"
    get "orders/:id" => "orders#show", as: :show_order
    #Order_Cart
    post "order/new" => "order_cart#create"
    #Addresses
    get "addresses" => "addresses#index"
    get "addresses/:id/edit" => "addresses#edit", as: :edit_address
    post "addresses" => "addresses#create", as: :create_address
    patch "addresses/:id" => "addresses#update", as: :update_address
    delete "addresses/:id" => "addresses#destroy", as: :destroy_address
  end

  namespace :admin do
    #Homes
    get "/" => "homes#top"
    #Items
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    #Genres
    get "genres" => "genres#index"
    post "genres" => "genres#create"
    get "genres/:id/edit" => "genres#edit", as: :edit
    patch "genres/:id" => "genres#update", as: :update_genre
    #Customers
    get "customers" => "customers#index"
    get "customers/:id" => "customers#show"
    get "customers/:id/edit" => "customers#edit", as: :edit_customers
    patch "customers/:id" => "customers#update", as: :update_customer
    #Orders
    get "orders/:id" => "orders#show", as: :order
    patch "orders/:id" => "orders#update", as: :order_update
    #Order_Details
    patch "order_details/:id" => "order_details#update", as: :order_detail_update
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}



end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true
  has_many :order
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses,  dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders,     dependent: :destroy
  has_many :order_carts,dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_active == false)
  end

  def lsname
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_carts
  has_many :cart_items

  def get_image
    image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer,optional: true
  belongs_to :address,optional: true
  has_many :order_carts, dependent: :destroy

 enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_cart.rb
class OrderCart < ApplicationRecord
  belongs_to :item,optional: true
  belongs_to :customer,optional: true
  belongs_to :order,optional: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active )
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders =Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end



  private
  def item_params
    params.require(:item).permit(:genre_id, :price,  :name, :image, :introduction, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.all

  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order(@order)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<%= form_with model: @customer, url: admin_update_customer_path, method: :patch do |f| %>

  <table>
    <tr>
      <td><h4>会員ID</h4></td>
      <td><%= f.text_field :id %></td>
    </tr>
    <tr>
      <td><h4>氏名</h4></td>
      <td><%= f.text_field :last_name %></td>
      <td><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <td><h4>フリガナ</h4></td>
      <td><%= f.text_field :last_name_kana %></td>
      <td><%= f.text_field :first_name_kana %></td>
    </tr>
    <tr>
      <td><h4>郵便番号</h4></td>
      <td><%= f.text_field :postal_code %></td>
    </tr>
    <tr>
      <td><h4>住所</h4></td>
      <td><%= f.text_field :address %></td>
    </tr>
    <tr>
      <td><h4>電話番号</h4></td>
      <td><%= f.text_field :telephone_number %></td>
    </tr>
    <tr>
      <td><h4>メールアドレス</h4></td>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <td><h4>会員ステータス</h4></td>
      <td><%= f.text_field :is_active %></td>
    </tr>
  </table>
  <%= f.submit '変更を保存' %>


<% end %>

app/views/admin/customers/index.html.erb
<thead>
  <tr>
    <th></th>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
    <th colspan="3"></th>
  </tr>
</thead>
<tbody>
  <% @customers.each do |cus| %>
    <tr>
      <th><%= cus.id %></th>
      <th>
        <%= link_to admin_edit_customers_path(cus.id) do %>
          <%= cus.last_name %>
          <%= cus.first_name %>
        <% end %>
      </th>
      <th><%= cus.email %></th>
      <th><%= cus.is_active %></th>
      <th colspan="3"></th>
    </tr>
  <% end %>
</tbody>

app/views/admin/customers/show.html.erb
<table class="table">
  <tr>
    <td>
      <lable>会員ID</lable>
      <%= @customer.id %>
    </td>
  </tr>
  <tr>
    <td>
      <lable>氏名</lable>
      <%= @customer.last_name %><%= @customer.first_name %>
    </td>
  </tr>
  <tr>
    <td>
      <lable>フリガナ</lable>
      <%= @customer.last_name_kana %><%= @customer.first_name_kana %>
    </td>
  </tr>
  <tr>
    <td>
      <lable>郵便番号</lable>
      <%= @customer.postal_code %>
    </td>
  </tr>
  <tr>
    <td>
      <lable>住所</lable>
      <%= @customer.address %>
    </td>
  </tr>
  <tr>
    <td>
      <lable>電話番号</lable>
      <%= @customer.telephone_number %>
    </td>
  </tr>
  <tr>
    <td>
      <lable>メールアドレス</lable>
      <%= @customer.email %>
    </td>
  </tr>
  <tr>
    <td>
      <lable>会員ステータス</lable>
      <%= @customer.is_active %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to "編集する", admin_edit_customers_path(@customer.id) %>
    </td>
    <td>
      <%= link_to "注文履歴一覧を見る", admin_customers_path %>
    </td>
  </tr>
</table>