config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'
  namespace :public do
    #Homes

    get 'about' => "homes#about"
    #Items
    resources :items, only: [:index, :show]
    #Registration
    resources :registrations, only: [:new, :create]
    #Sessions
    resources :sessions, only: [:new, :create, :destroy]
    #Customers
    get "customers/home" => "customers#show"
    get "customers/edit" => "customers#edit"
    patch "customers" => "customers#update"
    get "customers/confimation" => "customers#confimation"
    patch "customers/confimation" => "customers#withdraw", as: :withdraw_customer
    #Cart_Items
    get "cart_items" => "cart_items#index"
    patch "cart_items/:id" => "cart_items#update", as: :update_cart_item
    delete "cart_items/:id/destroy" => "cart_items#destroy", as: :destroy_cart_item
    delete "cart_items/destroy_all" => "cart_items#destroy_all", as: :destroy_all_cart_item
    post "cart_items" => "cart_items#create", as: :create_cart_item
    #Orders
    get "orders" => "orders#index"
    get "orders/new" => "orders#new"
    post "orders/new" => "orders#create"
    post "orders/confimation" => "orders#confimation"
    get "orders/thanks" => "orders#thanks"
    get "orders/:id" => "orders#show", as: :show_order
    #Order_Cart
    post "order/new" => "order_cart#create"
    #Addresses
    get "addresses" => "addresses#index"
    get "addresses/:id/edit" => "addresses#edit", as: :edit_address
    post "addresses" => "addresses#create", as: :create_address
    patch "addresses/:id" => "addresses#update", as: :update_address
    delete "addresses/:id" => "addresses#destroy", as: :destroy_address
  end

  namespace :admin do
    #Homes
    get "/" => "homes#top"
    #Items
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    #Genres
    get "genres" => "genres#index"
    post "genres" => "genres#create"
    get "genres/:id/edit" => "genres#edit", as: :edit
    patch "genres/:id" => "genres#update", as: :update_genre
    #Customers
    get "customers" => "customers#index"
    get "customers/:id" => "customers#show"
    get "customers/:id/edit" => "customers#edit", as: :edit_customers
    patch "customers/:id" => "customers#update", as: :update_customer
    #Orders
    get "orders/:id" => "orders#show", as: :order
    patch "orders/:id" => "orders#update", as: :order_update
    #Order_Details
    patch "order_details/:id" => "order_details#update", as: :order_detail_update
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}



end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true
  has_many :order
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses,  dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders,     dependent: :destroy
  has_many :order_carts,dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_active == false)
  end

  def lsname
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_carts
  has_many :cart_items

  def get_image
    image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer,optional: true
  belongs_to :address,optional: true
  has_many :order_carts, dependent: :destroy

 enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_cart.rb
class OrderCart < ApplicationRecord
  belongs_to :item,optional: true
  belongs_to :customer,optional: true
  belongs_to :order,optional: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders =Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end



  private
  def item_params
    params.require(:item).permit(:genre_id, :price,  :name, :image, :introduction, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.all

  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order(@order)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end


  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>

<%= form_with model: @genre, url: admin_update_genre_path(@genre.id), method: :patch do |f| %>

  <h4>ジャンル名</h4>
  <%= f.text_field :name %>

  <%= f.submit '変更を保存' %>

<% end %>

app/views/admin/genres/index.html.erb
<h2>ジャンル一覧・追加</h2>

<%= form_with model: @genre, url:'/admin/genres', method: :post do |f| %>
  <label>ジャンル名</label>
  <%= f.text_field :name %>
  <%= f.submit '新規登録' %>
<% end %>
<thead>
  <tr><th>ジャンル</th></tr>
</thead>
<tbody>
  <% @genres.each do |genre| %>
    <tr>
      <th>
        <%= genre.name %>
        <%= link_to admin_edit_path(genre.id) do %>
          編集する
        <% end %>
      </th>
    </tr>
  <% end %>
</tbody>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>

<%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>

  <h4>商品画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <h4>商品名</h4>
  <%= f.text_field :name %>

  <h4>商品説明</h4>
  <%= f.text_area :introduction %>

  <h4>ジャンル</h4>
  <%= f.collection_select :genre_id, Genre.all, :id, :name %>

  <h4>税抜価格</h4>
  <%= f.text_field :price %>
  <h4>円</h4>

  <%= f.submit '変更を保存' %>

<% end %>

app/views/admin/items/index.html.erb
<h2>商品一覧</h2>
<%= link_to "新規登録",new_admin_item_path %>
<table>
  <thead>
    <tr>
      <th></th>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <th></th>
        <th><%= item.id %></th>
        <th>
         <%= link_to admin_item_path(item.id) do %>
           <%= item.name %>
         <% end %>
        </th>
        <th><%= item.price %></th>
         <th><%= item.genre.name %></th>
         <th colspan="3"></th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/items/new.html.erb
<label>商品新規登録</label>

<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

  <div class="form-group">
    <lable>商品画像</lable>
    <%= f.file_field :image, accept: "image/*" %>
  </div>
  <div class="form-group">
    <label>商品名</label>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <label>商品説明</label>
    <%= f.text_area :introduction %>
  </div>
  <div class="form-group">
    <label>ジャンル</label>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, { include_blank: '--選択してください--'} %>
  </div>
  <div class="form-group">
    <label>税抜価格</label>
    <%= f.text_field :price %>円
  </div>
  <div class="form-group">
    <%= f.submit '新規登録' %>
  </div>
<% end %>

</div>

app/views/admin/items/show.html.erb
<table class="table">
  <tr>
    <td>
      <lable>商品名</lable>
      <%= @item.name %>
    </td>
  </tr>
  <tr>
    <td>
      <lable>商品紹介</lable>
      <%= @item.introduction %>
    </td>
  </tr>
  <tr>
    <td>
      <lable>ジャンル</lable>
      <%= @item.genre.name %>
    </td>
  </tr>
  <tr>
    <td>
      <div class="price">
        <lable>税込価格</lable>
        <lable>(税抜価格)</lable>
      </div>
      <%= @item.price %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to "編集する", edit_admin_item_path(@item.id) %>
    </td>
  </tr>
</table>

app/views/admin/orders/show.html.erb
<table>
  <tr>
    <td>購入日時</td>
    <td>購入者</td>
    <td>注文個数</td>
    <td colspan="5"></td>
  </tr>
  <% @order.each do |order| %>
    <table>
      <tr>
        <td><%= order.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= order.customer.name %></td>
        <td><%= order.order_cart.amount %></td>
        <td colspan="5"></td>
      </tr>
    </table>
  <% end %>
</table>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>