config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'
  namespace :public do
    #Homes

    get 'about' => "homes#about"
    #Items
    resources :items, only: [:index, :show]
    #Registration
    resources :registrations, only: [:new, :create]
    #Sessions
    resources :sessions, only: [:new, :create, :destroy]
    #Customers
    get "customers/home" => "customers#show"
    get "customers/edit" => "customers#edit"
    patch "customers" => "customers#update"
    get "customers/confimation" => "customers#confimation"
    patch "customers/confimation" => "customers#withdraw", as: :withdraw_customer
    #Cart_Items
    get "cart_items" => "cart_items#index"
    patch "cart_items/:id" => "cart_items#update", as: :update_cart_item
    delete "cart_items/:id/destroy" => "cart_items#destroy", as: :destroy_cart_item
    delete "cart_items/destroy_all" => "cart_items#destroy_all", as: :destroy_all_cart_item
    post "cart_items" => "cart_items#create", as: :create_cart_item
    #Orders
    get "orders" => "orders#index"
    get "orders/new" => "orders#new"
    post "orders/new" => "orders#create"
    post "orders/confimation" => "orders#confimation"
    get "orders/thanks" => "orders#thanks"
    get "orders/:id" => "orders#show", as: :show_order
    #Order_Cart
    post "order/new" => "order_cart#create"
    #Addresses
    get "addresses" => "addresses#index"
    get "addresses/:id/edit" => "addresses#edit", as: :edit_address
    post "addresses" => "addresses#create", as: :create_address
    patch "addresses/:id" => "addresses#update", as: :update_address
    delete "addresses/:id" => "addresses#destroy", as: :destroy_address
  end

  namespace :admin do
    #Homes
    get "/" => "homes#top"
    #Items
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    #Genres
    get "genres" => "genres#index"
    post "genres" => "genres#create"
    get "genres/:id/edit" => "genres#edit", as: :edit
    patch "genres/:id" => "genres#update", as: :update_genre
    #Customers
    get "customers" => "customers#index"
    get "customers/:id" => "customers#show"
    get "customers/:id/edit" => "customers#edit", as: :edit_customers
    patch "customers/:id" => "customers#update", as: :update_customer
    #Orders
    get "orders/:id" => "orders#show", as: :order
    patch "orders/:id" => "orders#update", as: :order_update
    #Order_Details
    patch "order_details/:id" => "order_details#update", as: :order_detail_update
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}



end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true
  has_many :order
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses,  dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders,     dependent: :destroy
  has_many :order_carts,dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_active == false)
  end

  def lsname
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_carts
  has_many :cart_items

  def get_image
    image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer,optional: true
  belongs_to :address,optional: true
  has_many :order_carts, dependent: :destroy

 enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_cart.rb
class OrderCart < ApplicationRecord
  belongs_to :item,optional: true
  belongs_to :customer,optional: true
  belongs_to :order,optional: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders =Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end



  private
  def item_params
    params.require(:item).permit(:genre_id, :price,  :name, :image, :introduction, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="boxer">
      <div>
  　　<h3 class="h">LOGO</h3>
　　　</div>
      <% if customer_signed_in? %>
      <div class="bo">
      <table class="sss">
        <tr>
          <td>
            <li class="lis">
              <%= link_to "マイページ", public_customers_home_path %>
            </li>
          </td>
          <td>
            <li class="lis">
              <%= link_to "商品一覧", public_items_path %>
            </li>
          </td>
          <td>
            <li class="lis">
              <%= link_to "カート", public_cart_items_path %>
            </li>
          </td>
          <td>
            <li class="lis">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
            </li>
          </td>
        </tr>
      </table>
      </div>
      <% elsif admin_signed_in? %>
      <div class="bo">
      <table class="sss">
        <tr>
          <td>
            <li class="lis">
              <%= link_to "商品一覧", admin_items_path %>
            </li>
          </td>
          <td>
            <li class="lis">
              <%= link_to "会員一覧", admin_customers_path %>
            </li>
          </td>
          <td>
            <li class="lis">
              <%= link_to "注文履歴一覧", admin_path %>
            </li>
          </td>
          <td>
            <li class="lis">
              <%= link_to "ジャンル一覧", admin_genres_path %>
            </li>
          </td>
          <td>
            <li class="lis">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
            </li>
          </td>
        </tr>
      </table>
      </div>
      <% else %>
      <div class="bo">
      <table class="sss">
        <tr>
          <td>
            <li class="lis">
              <%= link_to "About", public_about_path %>
            </li>
          </td>
          <td>
            <li class="lis">
              <%= link_to "商品一覧", public_items_path %>
            </li>
          </td>
          <td>
            <li class="lis">
              <%= link_to "新規登録", new_customer_registration_path %>
            </li>
          </td>
          <td>
            <li class="lis">
              <%= link_to "ログイン", new_customer_session_path %>
            </li>
          </td>
        </tr>
      </table>
      </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
  <footer class="fot">
    
  </footer>
</html>